<?php

namespace Database\Seeders;

use App\Models\Menu\UsersGrant;
use Illuminate\Database\Seeder;

class GrantsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        UsersGrant::insert([
            ['permission_id' => 'dashboard',
                'employee_id' => 1],
            ['permission_id' => 'totalsale',
                'employee_id' => 1],
            ['permission_id' => 'totalpurchase',
                'employee_id' => 1],
            ['permission_id' => 'customers',
                'employee_id' => 1],
            ['permission_id' => 'edit_customers',
                'employee_id' => 1],
            ['permission_id' => 'delete_customers',
                'employee_id' => 1],
            ['permission_id' => 'add_customers',
                'employee_id' => 1],
            ['permission_id' => 'view_customers',
                'employee_id' => 1],
            ['permission_id' => 'suppliers',
                'employee_id' => 1],
            ['permission_id' => 'edit_suppliers',
                'employee_id' => 1],
            ['permission_id' => 'delete_suppliers',
                'employee_id' => 1],
            ['permission_id' => 'add_suppliers',
                'employee_id' => 1],
            ['permission_id' => 'view_suppliers',
                'employee_id' => 1],
            ['permission_id' => 'sales',
                'employee_id' => 1],
            ['permission_id' => 'negativebilling',
                'employee_id' => 1],
            ['permission_id' => 'edit_rate',
                'employee_id' => 1],
            ['permission_id' => 'cash_sales',
                'employee_id' => 1],
            ['permission_id' => 'credit_sales',
                'employee_id' => 1],
            ['permission_id' => 'cash_sales_return',
                'employee_id' => 1],
            ['permission_id' => 'credit_sales_return',
                'employee_id' => 1],
            ['permission_id' => 'quotation',
                'employee_id' => 1],
            ['permission_id' => 'workorder',
                'employee_id' => 1],
            ['permission_id' => 'purchase',
                'employee_id' => 1],
            ['permission_id' => 'requisition',
                'employee_id' => 1],
            ['permission_id' => 'new_cash_purchase',
                'employee_id' => 1],
            ['permission_id' => 'cash_purchase_return',
                'employee_id' => 1],
            ['permission_id' => 'new_credit_purchase',
                'employee_id' => 1],
            ['permission_id' => 'credit_purchase_return',
                'employee_id' => 1],
            ['permission_id' => 'employee',
                'employee_id' => 1],
            ['permission_id' => 'edit_employee',
                'employee_id' => 1],
            ['permission_id' => 'delete_employee',
                'employee_id' => 1],
            ['permission_id' => 'add_employee',
                'employee_id' => 1],
            ['permission_id' => 'view_employee',
                'employee_id' => 1],
            ['permission_id' => 'items',
                'employee_id' => 1],
            ['permission_id' => 'edit_items',
                'employee_id' => 1],
            ['permission_id' => 'delete_items',
                'employee_id' => 1],
            ['permission_id' => 'add_items',
                'employee_id' => 1],
            ['permission_id' => 'view_items',
                'employee_id' => 1],
            ['permission_id' => 'opening_stock',
                'employee_id' => 1],
            ['permission_id' => 'bundleditems',
                'employee_id' => 1],
            ['permission_id' => 'edit_bundleditems',
                'employee_id' => 1],
            ['permission_id' => 'delete_bundleditems',
                'employee_id' => 1],
            ['permission_id' => 'add_bundleditems',
                'employee_id' => 1],
            ['permission_id' => 'view_bundleditems',
                'employee_id' => 1],
            ['permission_id' => 'accounts',
                'employee_id' => 1],
            ['permission_id' => 'reports',
                'employee_id' => 1],
            ['permission_id' => 'messages',
                'employee_id' => 1],
            ['permission_id' => 'configurations',
                'employee_id' => 1],
        ]);
    }
}
